import type { Metadata } from "next";
import { Poppins, Satisfy } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/global/Navbar";

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["400"],
});

const satisfy = Satisfy({
    variable: "--font-satisfy",
    subsets: ["latin"],
    weight: "400",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${poppins.variable} ${satisfy.variable} antialiased`}
                suppressHydrationWarning
            >
                <Navbar />
                {children}
            </body>
        </html>
    );
}
