import { bg_images } from "./image";

export const tourData = [
    {
        id: 1,
        title: "Explore Dhaka Lalbag Fort",
        image: bg_images.image1.src,
        price: 250,
        rating: 4.9,
        reviews: 1327,
        duration: "3 days 2 nights",
        people: 4,
        location: "Lalbag Fort, Dhaka",
        category: "Historical",
    },
    {
        id: 2,
        title: "Adventure in Sundarbans",
        image: bg_images.image2.src,
        price: 300,
        rating: 4.8,
        reviews: 1200,
        duration: "5 days 4 nights",
        people: 6,
        location: "Sundarbans, Khulna",
        category: "Nature",
    },
    {
        id: 3,
        title: "Cultural Tour of Srimangal",
        image: bg_images.image3.src,
        price: 200,
        rating: 4.7,
        reviews: 800,
        duration: "2 days 1 night",
        people: 2,
        location: "Srimangal, Moulvibazar",
        category: "Sailboat",
    },
    {
        id: 4,
        title: "Historical Tour of Paharpur",
        image: bg_images.image4.src,
        price: 150,
        rating: 4.6,
        reviews: 600,
        duration: "1 day",
        people: 1,
        location: "Paharpur, Naogaon",
        category: "Historical",
    },
    {
        id: 5,
        title: "Nature Walk in Bandarban",
        image: bg_images.image1.src,
        price: 180,
        rating: 4.9,
        reviews: 950,
        duration: "3 days 2 nights",
        people: 3,
        location: "Bandarban, Chittagong",
        category: "Historical",
    },
];
